package unit5;

import java.util.Objects;

/**
 *
 * @author Raidi
 */
public class Student {

    //Creates instance variables
    private int studentNumber;
    private String firstName;
    private String lastName;

    //Constructor for creating a random Student object if no parameters passed
    public Student() {
        this.studentNumber = -1;
    }

    //Constructor for creating a student with a student number generated by client
    public Student(int studentNumber) {
        this.studentNumber = studentNumber;
    }

    //Constructor for client giving a student a first and last name.
    public Student(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    //SETTERS AND GETTERS
    public int getStudentNumber() {
        return studentNumber;
    }

    public void setStudentNumber(int studentNumber) {
        this.studentNumber = studentNumber;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    //Converts variable data into a string that the client can understand
    @Override
    public String toString() {
        return "Student{" + "studentNumber=" + studentNumber + ", firstName=" + firstName + ", lastName=" + lastName;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        return hash;
    }

    //Checks whether objects are equal by comparing studentNumber, firstName, and lastName
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Student other = (Student) obj;
        if (this.studentNumber != other.studentNumber) {
            return false;
        }
        if (!Objects.equals(this.firstName, other.firstName)) {
            return false;
        }
        if (!Objects.equals(this.lastName, other.lastName)) {
            return false;
        }
        return true;
    }

}
